version: "2"
services:
  webserver1:
    container_name: webserver1
    build:
      context: ./app/
    volumes:
      - ./app/:/usr/share/nginx/html/
    ports:
      - "3002:80"
    environment:
      - kafka=https://127.0.0.1:9978/