version: "2"
services:
  webserver1:
    container_name: webserver1
    build:
      context: ./app/
      args:
        - kafka_url=http://localhost:8083/
    volumes:
      - ./app/:/usr/share/nginx/html/
    ports:
      - "3002:80"
    